# frozen_string_literal: true

# Runar indexing enhancement for the Ruby LSP.
#
# Teaches the LSP indexer about `prop :name, Type` declarations so that:
#
#   - The accessor method(s) generated by `prop` appear in completion lists.
#   - `@name` instance variables are indexed for go-to-definition.
#
# How it works:
#   Ruby LSP calls on_call_node_enter for every method call found during
#   indexing. We intercept calls whose name is :prop and extract the
#   symbol argument (the property name) and the constant argument (the
#   Runar type). We then register:
#     1. A reader method via the public add_method API.
#     2. A writer method when the prop is not declared readonly.
#     3. The backing @name instance variable directly via the index.
#
# File scoping:
#   Runar contract files use the .runar.rb extension. We skip indexing
#   for any file that does not match this pattern so that regular Ruby
#   files in the same project are unaffected.

module RubyLsp
  module Runar
    class IndexingEnhancement < ::RubyIndexer::Enhancement
      PROP_METHOD_NAME = :prop #: Symbol

      # Called by the LSP indexer for every CallNode encountered while
      # parsing a file.
      #
      # node - Prism::CallNode
      def on_call_node_enter(node)
        return unless runar_file?
        return unless node.name == PROP_METHOD_NAME
        return unless @listener.current_owner

        arguments = node.arguments&.arguments
        return unless arguments && arguments.length >= 2

        # First argument must be a symbol literal: prop :name, Type
        name_node = arguments[0]
        return unless name_node.is_a?(Prism::SymbolNode)

        prop_name = name_node.value
        return unless prop_name

        # Determine whether the call includes `readonly: true`.
        # We look for a keyword hash among the arguments.
        is_readonly = extract_readonly_keyword(arguments)

        # Register the reader method (always present).
        register_reader(prop_name, node)

        # Register the writer method only when the prop is not readonly.
        register_writer(prop_name, node) unless is_readonly

        # Register the backing instance variable so that @name is known
        # to the index for go-to-definition and hover.
        register_instance_variable("@#{prop_name}", node)
      end

      # @overridable — required by the Enhancement interface.
      def on_call_node_leave(_node); end

      private

      # Returns true when the file currently being indexed is a Runar
      # contract file (i.e., its path ends with .runar.rb).
      def runar_file?
        uri = @listener.instance_variable_get(:@uri)
        return false unless uri

        uri.to_s.end_with?('.runar.rb')
      end

      # Scans the argument list for a keyword hash containing readonly: true.
      # Returns true when the prop should generate a reader only.
      def extract_readonly_keyword(arguments)
        keyword_hash = arguments.find { |a| a.is_a?(Prism::KeywordHashNode) }
        return false unless keyword_hash

        keyword_hash.elements.any? do |pair|
          next false unless pair.is_a?(Prism::AssocNode)

          key = pair.key
          value = pair.value
          key.is_a?(Prism::SymbolNode) &&
            key.value == 'readonly' &&
            value.is_a?(Prism::TrueNode)
        end
      end

      # Registers a zero-parameter reader method with the LSP index.
      def register_reader(prop_name, node)
        @listener.add_method(
          prop_name,
          node.location,
          [RubyIndexer::Entry::Signature.new([])],
          visibility: :public,
          comments: "Runar prop reader for :#{prop_name}",
        )
      end

      # Registers a one-parameter writer method with the LSP index.
      def register_writer(prop_name, node)
        @listener.add_method(
          "#{prop_name}=",
          node.location,
          [RubyIndexer::Entry::Signature.new(
            [RubyIndexer::Entry::RequiredParameter.new(name: :value)],
          )],
          visibility: :public,
          comments: "Runar prop writer for :#{prop_name}",
        )
      end

      # Registers the backing instance variable with the LSP index.
      #
      # This gives editors go-to-definition and hover information for
      # @name references inside contract method bodies.
      #
      # We access @index and @uri via instance_variable_get because there
      # is no public API on DeclarationListener for adding instance
      # variable entries. The rescue guard means a future ruby-lsp API
      # change will silently degrade rather than crash the LSP.
      def register_instance_variable(ivar_name, node)
        index = @listener.instance_variable_get(:@index)
        uri   = @listener.instance_variable_get(:@uri)
        cache = @listener.instance_variable_get(:@code_units_cache)
        return unless index && uri

        owner = @listener.current_owner

        location = if cache
                     RubyIndexer::Location.from_prism_location(node.location, cache)
                   else
                     RubyIndexer::Location.from_prism_location(node.location)
                   end

        index.add(RubyIndexer::Entry::InstanceVariable.new(
          index.configuration,
          ivar_name,
          uri,
          location,
          "Runar prop: #{ivar_name}",
          owner,
        ))
      rescue StandardError
        # Degrade silently — instance variable indexing is best-effort.
        # If the ruby-lsp internal API changes, readers and writers
        # (registered via the public API above) still work correctly.
      end
    end
  end
end
