/**
 * Baby Bear field arithmetic — Plonky3-generated test vector validation.
 *
 * Uses the Rúnar interpreter (TestContract) to validate all 829 test vectors
 * generated by Plonky3's p3-baby-bear reference implementation.
 *
 * This runs without a regtest node — the interpreter executes Baby Bear
 * field arithmetic directly. For on-chain validation, see the integration
 * tests in integration/go/ and integration/ts/.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TestContract } from 'runar-testing';

const __dirname = dirname(fileURLToPath(import.meta.url));
const VECTORS_DIR = join(__dirname, 'vectors');

interface TestVector {
  op: string;
  a: number;
  b?: number;
  expected: number;
  description: string;
}

interface VectorFile {
  field: string;
  prime: number;
  vectors: TestVector[];
}

function loadVectors(filename: string): VectorFile {
  return JSON.parse(readFileSync(join(VECTORS_DIR, filename), 'utf-8'));
}

// Contract sources with named params matching TestContract call convention
const bbAddSource = `
import { SmartContract, assert, bbFieldAdd } from 'runar-lang';

class BBAddVec extends SmartContract {
  constructor() { super(); }
  public verify(a: bigint, b: bigint, expected: bigint) {
    assert(bbFieldAdd(a, b) === expected);
  }
}
`;

const bbSubSource = `
import { SmartContract, assert, bbFieldSub } from 'runar-lang';

class BBSubVec extends SmartContract {
  constructor() { super(); }
  public verify(a: bigint, b: bigint, expected: bigint) {
    assert(bbFieldSub(a, b) === expected);
  }
}
`;

const bbMulSource = `
import { SmartContract, assert, bbFieldMul } from 'runar-lang';

class BBMulVec extends SmartContract {
  constructor() { super(); }
  public verify(a: bigint, b: bigint, expected: bigint) {
    assert(bbFieldMul(a, b) === expected);
  }
}
`;

const bbInvSource = `
import { SmartContract, assert, bbFieldInv } from 'runar-lang';

class BBInvVec extends SmartContract {
  constructor() { super(); }
  public verify(a: bigint, expected: bigint) {
    assert(bbFieldInv(a) === expected);
  }
}
`;

describe('Baby Bear Vectors — Addition (Plonky3)', () => {
  const vf = loadVectors('babybear_add.json');
  const c = TestContract.fromSource(bbAddSource, {});

  it.each(vf.vectors.map((v, i) => [i, v.description, v] as const))(
    'vec[%d]: %s',
    (_i, _desc, vec) => {
      const r = c.call('verify', {
        a: BigInt(vec.a),
        b: BigInt(vec.b!),
        expected: BigInt(vec.expected),
      });
      expect(r.success).toBe(true);
    },
  );
});

describe('Baby Bear Vectors — Subtraction (Plonky3)', () => {
  const vf = loadVectors('babybear_sub.json');
  const c = TestContract.fromSource(bbSubSource, {});

  it.each(vf.vectors.map((v, i) => [i, v.description, v] as const))(
    'vec[%d]: %s',
    (_i, _desc, vec) => {
      const r = c.call('verify', {
        a: BigInt(vec.a),
        b: BigInt(vec.b!),
        expected: BigInt(vec.expected),
      });
      expect(r.success).toBe(true);
    },
  );
});

describe('Baby Bear Vectors — Multiplication (Plonky3)', () => {
  const vf = loadVectors('babybear_mul.json');
  const c = TestContract.fromSource(bbMulSource, {});

  it.each(vf.vectors.map((v, i) => [i, v.description, v] as const))(
    'vec[%d]: %s',
    (_i, _desc, vec) => {
      const r = c.call('verify', {
        a: BigInt(vec.a),
        b: BigInt(vec.b!),
        expected: BigInt(vec.expected),
      });
      expect(r.success).toBe(true);
    },
  );
});

describe('Baby Bear Vectors — Inverse (Plonky3)', () => {
  const vf = loadVectors('babybear_inv.json');
  const c = TestContract.fromSource(bbInvSource, {});

  it.each(vf.vectors.map((v, i) => [i, v.description, v] as const))(
    'vec[%d]: %s',
    (_i, _desc, vec) => {
      const r = c.call('verify', {
        a: BigInt(vec.a),
        expected: BigInt(vec.expected),
      });
      expect(r.success).toBe(true);
    },
  );
});
