/**
 * Baby Bear quartic extension field — Plonky3-generated test vector validation.
 *
 * Validates bbExt4Mul0..3 and bbExt4Inv0..3 builtins against test vectors
 * generated by Plonky3's p3-baby-bear (BinomialExtensionField<BabyBear, 4>).
 *
 * Uses the Rúnar interpreter (TestContract) — no regtest node needed.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TestContract } from 'runar-testing';

const __dirname = dirname(fileURLToPath(import.meta.url));
const VECTORS_DIR = join(__dirname, 'vectors');

interface Ext4TestVector {
  op: string;
  a: [number, number, number, number];
  b?: [number, number, number, number];
  expected: [number, number, number, number];
  description: string;
}

interface Ext4VectorFile {
  field: string;
  prime: number;
  extension_degree: number;
  vectors: Ext4TestVector[];
}

function loadVectors(filename: string): Ext4VectorFile {
  return JSON.parse(readFileSync(join(VECTORS_DIR, filename), 'utf-8'));
}

// Contract source for ext4 multiplication verification
const ext4MulSource = `
import { SmartContract, assert, bbExt4Mul0, bbExt4Mul1, bbExt4Mul2, bbExt4Mul3 } from 'runar-lang';

class BBExt4MulTest extends SmartContract {
  constructor() { super(); }
  public verify(
    a0: bigint, a1: bigint, a2: bigint, a3: bigint,
    b0: bigint, b1: bigint, b2: bigint, b3: bigint,
    e0: bigint, e1: bigint, e2: bigint, e3: bigint
  ) {
    assert(bbExt4Mul0(a0, a1, a2, a3, b0, b1, b2, b3) === e0);
    assert(bbExt4Mul1(a0, a1, a2, a3, b0, b1, b2, b3) === e1);
    assert(bbExt4Mul2(a0, a1, a2, a3, b0, b1, b2, b3) === e2);
    assert(bbExt4Mul3(a0, a1, a2, a3, b0, b1, b2, b3) === e3);
  }
}
`;

// Contract source for ext4 inverse verification
const ext4InvSource = `
import { SmartContract, assert, bbExt4Inv0, bbExt4Inv1, bbExt4Inv2, bbExt4Inv3 } from 'runar-lang';

class BBExt4InvTest extends SmartContract {
  constructor() { super(); }
  public verify(
    a0: bigint, a1: bigint, a2: bigint, a3: bigint,
    e0: bigint, e1: bigint, e2: bigint, e3: bigint
  ) {
    assert(bbExt4Inv0(a0, a1, a2, a3) === e0);
    assert(bbExt4Inv1(a0, a1, a2, a3) === e1);
    assert(bbExt4Inv2(a0, a1, a2, a3) === e2);
    assert(bbExt4Inv3(a0, a1, a2, a3) === e3);
  }
}
`;

describe('Baby Bear Ext4 Vectors — Multiplication (Plonky3)', () => {
  const vf = loadVectors('babybear_ext4_mul.json');
  const c = TestContract.fromSource(ext4MulSource, {});

  it.each(vf.vectors.map((v, i) => [i, v.description, v] as const))(
    'vec[%d]: %s',
    (_i, _desc, vec) => {
      const r = c.call('verify', {
        a0: BigInt(vec.a[0]), a1: BigInt(vec.a[1]),
        a2: BigInt(vec.a[2]), a3: BigInt(vec.a[3]),
        b0: BigInt(vec.b![0]), b1: BigInt(vec.b![1]),
        b2: BigInt(vec.b![2]), b3: BigInt(vec.b![3]),
        e0: BigInt(vec.expected[0]), e1: BigInt(vec.expected[1]),
        e2: BigInt(vec.expected[2]), e3: BigInt(vec.expected[3]),
      });
      expect(r.success).toBe(true);
    },
  );
});

describe('Baby Bear Ext4 Vectors — Inverse (Plonky3)', () => {
  const vf = loadVectors('babybear_ext4_inv.json');
  const c = TestContract.fromSource(ext4InvSource, {});

  it.each(vf.vectors.map((v, i) => [i, v.description, v] as const))(
    'vec[%d]: %s',
    (_i, _desc, vec) => {
      const r = c.call('verify', {
        a0: BigInt(vec.a[0]), a1: BigInt(vec.a[1]),
        a2: BigInt(vec.a[2]), a3: BigInt(vec.a[3]),
        e0: BigInt(vec.expected[0]), e1: BigInt(vec.expected[1]),
        e2: BigInt(vec.expected[2]), e3: BigInt(vec.expected[3]),
      });
      expect(r.success).toBe(true);
    },
  );
});
