/**
 * SHA-256 Merkle proof verification — test vector validation.
 *
 * Validates merkleRootSha256 against test vectors generated by the Rust
 * generator (standard SHA-256 Merkle trees). Tests both valid inclusion
 * proofs (computed root must match) and invalid proofs (must not match).
 *
 * Uses the Rúnar interpreter (TestContract) — no regtest node needed.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TestContract } from 'runar-testing';

const __dirname = dirname(fileURLToPath(import.meta.url));
const VECTORS_DIR = join(__dirname, 'vectors');

interface MerkleVector {
  tree_size: number;
  depth: number;
  leaf_index: number;
  leaf: string;
  proof: string;
  root: string;
  expected: 'accept' | 'reject';
  description: string;
}

interface MerkleVectorFile {
  hash: string;
  vectors: MerkleVector[];
}

function loadVectors(filename: string): MerkleVectorFile {
  return JSON.parse(readFileSync(join(VECTORS_DIR, filename), 'utf-8'));
}

// Group vectors by depth since the contract requires a compile-time constant depth.
function groupByDepth(vectors: MerkleVector[]): Map<number, MerkleVector[]> {
  const map = new Map<number, MerkleVector[]>();
  for (const v of vectors) {
    const arr = map.get(v.depth) ?? [];
    arr.push(v);
    map.set(v.depth, arr);
  }
  return map;
}

// Contract source template — depth is baked in as a literal.
function makeAcceptSource(depth: number): string {
  return `
import { SmartContract, assert, merkleRootSha256 } from 'runar-lang';
import type { ByteString } from 'runar-lang';

class MerkleAccept${depth} extends SmartContract {
  readonly expectedRoot: ByteString;
  constructor(expectedRoot: ByteString) { super(expectedRoot); this.expectedRoot = expectedRoot; }
  public verify(leaf: ByteString, proof: ByteString, index: bigint) {
    const root = merkleRootSha256(leaf, proof, index, ${depth}n);
    assert(root === this.expectedRoot);
  }
}
`;
}

function makeRejectSource(depth: number): string {
  return `
import { SmartContract, assert, merkleRootSha256 } from 'runar-lang';
import type { ByteString } from 'runar-lang';

class MerkleReject${depth} extends SmartContract {
  readonly expectedRoot: ByteString;
  constructor(expectedRoot: ByteString) { super(expectedRoot); this.expectedRoot = expectedRoot; }
  public verify(leaf: ByteString, proof: ByteString, index: bigint) {
    const root = merkleRootSha256(leaf, proof, index, ${depth}n);
    assert(root === this.expectedRoot);
  }
}
`;
}

describe('Merkle Inclusion Vectors (SHA-256)', () => {
  const vf = loadVectors('merkle_inclusion.json');
  const groups = groupByDepth(vf.vectors);

  for (const [depth, vectors] of groups) {
    describe(`depth ${depth}`, () => {
      const source = makeAcceptSource(depth);

      it.each(vectors.map((v, i) => [i, v.description, v] as const))(
        'vec[%d]: %s',
        (_i, _desc, vec) => {
          const c = TestContract.fromSource(source, {
            expectedRoot: vec.root,
          });
          const r = c.call('verify', {
            leaf: vec.leaf,
            proof: vec.proof,
            index: BigInt(vec.leaf_index),
          });
          expect(r.success).toBe(true);
        },
      );
    });
  }
});

describe('Merkle Rejection Vectors (SHA-256)', () => {
  const vf = loadVectors('merkle_rejection.json');
  const groups = groupByDepth(vf.vectors);

  for (const [depth, vectors] of groups) {
    describe(`depth ${depth}`, () => {
      const source = makeRejectSource(depth);

      // Filter out truncated-proof vectors — those have wrong proof length
      // for the depth constant and will fail at parse/compile, not at assert.
      const validLengthVecs = vectors.filter(
        (v) => v.proof.length / 2 === depth * 32,
      );
      const truncatedVecs = vectors.filter(
        (v) => v.proof.length / 2 !== depth * 32,
      );

      if (validLengthVecs.length > 0) {
        it.each(validLengthVecs.map((v, i) => [i, v.description, v] as const))(
          'vec[%d]: %s',
          (_i, _desc, vec) => {
            const c = TestContract.fromSource(source, {
              expectedRoot: vec.root,
            });
            const r = c.call('verify', {
              leaf: vec.leaf,
              proof: vec.proof,
              index: BigInt(vec.leaf_index),
            });
            // Rejection: the assert(root === expectedRoot) should FAIL
            expect(r.success).toBe(false);
          },
        );
      }

      if (truncatedVecs.length > 0) {
        it.each(truncatedVecs.map((v, i) => [i, v.description, v] as const))(
          'vec[%d] (truncated proof): %s',
          (_i, _desc, vec) => {
            const c = TestContract.fromSource(source, {
              expectedRoot: vec.root,
            });
            // Truncated proof: interpreter should error or produce wrong root
            const r = c.call('verify', {
              leaf: vec.leaf,
              proof: vec.proof,
              index: BigInt(vec.leaf_index),
            });
            expect(r.success).toBe(false);
          },
        );
      }
    });
  }
});
