// ---------------------------------------------------------------------------
// codegen/gen-typescript.ts — Generate typed TypeScript wrapper from artifact
// ---------------------------------------------------------------------------

import type { RunarArtifact } from 'runar-ir-schema';
import {
  getUserParams,
  getSdkArgParams,
  isTerminalMethod,
  isStatefulArtifact,
  getPublicMethods,
  safeMethodName,
  mapTypeToTS,
} from './common.js';

/**
 * Generate a typed TypeScript wrapper class from a compiled Runar artifact.
 *
 * The generated class wraps `RunarContract` and exposes typed methods
 * for each public contract method, with appropriate options types for
 * terminal vs state-mutating methods.
 */
export function generateTypescript(artifact: RunarArtifact): string {
  const name = artifact.contractName;
  const isStateful = isStatefulArtifact(artifact);
  const publicMethods = getPublicMethods(artifact);
  const hasStatefulMethods = isStateful && publicMethods.some((m) => !isTerminalMethod(m, isStateful));
  const hasTerminalMethods = publicMethods.some((m) => isTerminalMethod(m, isStateful));

  const lines: string[] = [];
  const emit = (line: string) => lines.push(line);
  const blank = () => lines.push('');

  // Header
  emit('// Generated by: runar codegen');
  emit(`// Source: ${name}`);
  emit('// Do not edit manually.');
  blank();

  // Imports
  emit("import { RunarContract, buildP2PKHScript } from 'runar-sdk';");
  emit("import type { Provider, Signer, TransactionData, DeployOptions, RunarArtifact, PreparedCall } from 'runar-sdk';");
  blank();

  // Result type alias
  emit('type CallResult = { txid: string; tx: TransactionData };');
  blank();

  // Terminal output type — accepts address (converted to P2PKH) or raw scriptHex
  if (hasTerminalMethods) {
    emit('export interface TerminalOutput {');
    emit('  satoshis: number;');
    emit('  /** Recipient address (converted to P2PKH script). */');
    emit('  address?: string;');
    emit('  /** Raw locking script hex (used if address is not provided). */');
    emit('  scriptHex?: string;');
    emit('}');
    blank();
  }

  // Options interfaces
  if (hasStatefulMethods) {
    emit(`export interface ${name}StatefulCallOptions {`);
    emit('  satoshis?: number;');
    emit('  changeAddress?: string;');
    emit('  changePubKey?: string;');
    emit('  newState?: Record<string, unknown>;');
    emit('  outputs?: Array<{ satoshis: number; state: Record<string, unknown> }>;');
    emit('}');
    blank();
  }

  // Class
  emit(`export class ${name}Contract {`);
  emit('  private readonly inner: RunarContract;');
  blank();

  // Constructor
  const ctorParams = artifact.abi.constructor.params;
  if (ctorParams.length > 0) {
    emit('  constructor(');
    emit('    artifact: RunarArtifact,');
    emit('    args: {');
    for (const p of ctorParams) {
      emit(`      ${p.name}: ${mapTypeToTS(p.type)};`);
    }
    emit('    },');
    emit('  ) {');
    const argsList = ctorParams.map((p) => `args.${p.name}`).join(', ');
    emit(`    this.inner = new RunarContract(artifact, [${argsList}]);`);
  } else {
    emit('  constructor(artifact: RunarArtifact) {');
    emit('    this.inner = new RunarContract(artifact, []);');
  }
  emit('  }');
  blank();

  // fromUtxo
  emit('  static fromUtxo(');
  emit('    artifact: RunarArtifact,');
  emit('    utxo: { txid: string; outputIndex: number; satoshis: number; script: string },');
  emit(`  ): ${name}Contract {`);
  emit(`    const instance = Object.create(${name}Contract.prototype) as ${name}Contract;`);
  emit('    (instance as any).inner = RunarContract.fromUtxo(artifact, utxo);');
  emit('    return instance;');
  emit('  }');
  blank();

  // fromTxId
  emit('  static async fromTxId(');
  emit('    artifact: RunarArtifact,');
  emit('    txid: string,');
  emit('    outputIndex: number,');
  emit('    provider: Provider,');
  emit(`  ): Promise<${name}Contract> {`);
  emit(`    const instance = Object.create(${name}Contract.prototype) as ${name}Contract;`);
  emit('    (instance as any).inner = await RunarContract.fromTxId(artifact, txid, outputIndex, provider);');
  emit('    return instance;');
  emit('  }');
  blank();

  // connect
  emit('  connect(provider: Provider, signer: Signer): void {');
  emit('    this.inner.connect(provider, signer);');
  emit('  }');
  blank();

  // deploy overloads
  emit('  async deploy(options?: DeployOptions): Promise<CallResult>;');
  emit('  async deploy(provider: Provider, signer: Signer, options?: DeployOptions): Promise<CallResult>;');
  emit('  async deploy(...args: unknown[]): Promise<CallResult> {');
  emit('    return (this.inner.deploy as Function)(...args);');
  emit('  }');
  blank();

  // deployWithWallet
  emit('  async deployWithWallet(options: { satoshis?: number; description?: string } = {}): Promise<{ txid: string; outputIndex: number }> {');
  emit('    return this.inner.deployWithWallet(options);');
  emit('  }');
  blank();

  // getLockingScript
  emit('  getLockingScript(): string {');
  emit('    return this.inner.getLockingScript();');
  emit('  }');
  blank();

  // contract getter
  emit('  get contract(): RunarContract {');
  emit('    return this.inner;');
  emit('  }');

  // Helper for terminal output conversion (emitted once if needed)
  if (hasTerminalMethods) {
    blank();
    emit('  private static resolveOutputs(outputs: TerminalOutput[]): Array<{ scriptHex: string; satoshis: number }> {');
    emit('    return outputs.map((o) => {');
    emit('      const scriptHex = o.scriptHex ?? buildP2PKHScript(o.address!);');
    emit('      return { scriptHex, satoshis: o.satoshis };');
    emit('    });');
    emit('  }');
  }

  // Methods
  for (const method of publicMethods) {
    blank();
    const userParams = getUserParams(method, isStateful);
    const isTerminal = isTerminalMethod(method, isStateful);
    const safeName = safeMethodName(method.name);

    // JSDoc
    if (isStateful) {
      emit(`  /** ${isTerminal ? 'Terminal' : 'State-mutating'} method: ${method.name} */`);
    }

    // Signature params
    const paramParts: string[] = [];
    for (const p of userParams) {
      paramParts.push(`${p.name}: ${p.tsType}`);
    }

    if (isTerminal && isStateful) {
      // Terminal stateful: require outputs
      paramParts.push('outputs: TerminalOutput[]');
    } else if (isStateful) {
      // State-mutating: optional options
      paramParts.push(`options?: ${name}StatefulCallOptions`);
    } else {
      // Stateless: optional outputs
      paramParts.push('outputs?: TerminalOutput[]');
    }

    if (paramParts.length <= 2) {
      emit(`  async ${safeName}(${paramParts.join(', ')}): Promise<CallResult> {`);
    } else {
      emit(`  async ${safeName}(`);
      for (let i = 0; i < paramParts.length; i++) {
        emit(`    ${paramParts[i]},`);
      }
      emit('  ): Promise<CallResult> {');
    }

    // Build args array: only SDK-visible params (excludes SigHashPreimage,
    // _changePKH, _changeAmount which the SDK handles internally).
    // Sig params are included as null (auto-computed by SDK).
    const sdkArgs = getSdkArgParams(method, isStateful);
    const argParts: string[] = [];
    for (const p of sdkArgs) {
      argParts.push(p.hidden ? 'null' : p.name);
    }
    const argsExpr = `[${argParts.join(', ')}]`;

    if (isTerminal && isStateful) {
      // Terminal: convert outputs to terminalOutputs
      emit(`    return this.inner.call('${method.name}', ${argsExpr}, {`);
      emit(`      terminalOutputs: ${name}Contract.resolveOutputs(outputs),`);
      emit('    });');
    } else if (!isStateful) {
      // Stateless: optionally convert outputs
      emit(`    const callOpts = outputs ? { terminalOutputs: ${name}Contract.resolveOutputs(outputs) } : undefined;`);
      emit(`    return this.inner.call('${method.name}', ${argsExpr}, callOpts);`);
    } else {
      // State-mutating: pass options through
      emit(`    return this.inner.call('${method.name}', ${argsExpr}, options);`);
    }
    emit('  }');

    // -----------------------------------------------------------------
    // prepareX / finalizeX — multi-signer support for methods with Sig params
    // -----------------------------------------------------------------
    const sigParams = sdkArgs.filter((p) => p.abiType === 'Sig');
    if (sigParams.length > 0) {
      blank();

      // --- prepareX ---
      const capitalizedName = safeName.charAt(0).toUpperCase() + safeName.slice(1);
      const prepareName = `prepare${capitalizedName}`;

      // prepareX has the same user-visible params minus Sig params
      const prepareUserParams = userParams.filter((p) => p.abiType !== 'Sig');
      const prepareParamParts: string[] = [];
      for (const p of prepareUserParams) {
        prepareParamParts.push(`${p.name}: ${p.tsType}`);
      }
      // Add the same options param as the main method
      if (isTerminal && isStateful) {
        prepareParamParts.push('outputs: TerminalOutput[]');
      } else if (isStateful) {
        prepareParamParts.push(`options?: ${name}StatefulCallOptions`);
      } else {
        prepareParamParts.push('outputs?: TerminalOutput[]');
      }

      if (prepareParamParts.length <= 2) {
        emit(`  async ${prepareName}(${prepareParamParts.join(', ')}): Promise<PreparedCall> {`);
      } else {
        emit(`  async ${prepareName}(`);
        for (const pp of prepareParamParts) emit(`    ${pp},`);
        emit('  ): Promise<PreparedCall> {');
      }

      // Body: call this.inner.prepareCall with same args array as call()
      if (isTerminal && isStateful) {
        emit(`    return this.inner.prepareCall('${method.name}', ${argsExpr}, {`);
        emit(`      terminalOutputs: ${name}Contract.resolveOutputs(outputs),`);
        emit('    });');
      } else if (!isStateful) {
        emit(`    const callOpts = outputs ? { terminalOutputs: ${name}Contract.resolveOutputs(outputs) } : undefined;`);
        emit(`    return this.inner.prepareCall('${method.name}', ${argsExpr}, callOpts);`);
      } else {
        emit(`    return this.inner.prepareCall('${method.name}', ${argsExpr}, options);`);
      }
      emit('  }');

      // --- finalizeX ---
      blank();
      const finalizeName = `finalize${capitalizedName}`;

      const finalizeParamParts = ['prepared: PreparedCall'];
      for (const sp of sigParams) {
        finalizeParamParts.push(`${sp.name}: string`);
      }

      if (finalizeParamParts.length <= 3) {
        emit(`  async ${finalizeName}(${finalizeParamParts.join(', ')}): Promise<CallResult> {`);
      } else {
        emit(`  async ${finalizeName}(`);
        for (const fp of finalizeParamParts) emit(`    ${fp},`);
        emit('  ): Promise<CallResult> {');
      }

      // Build signatures map: { argIndex: sigParamName }
      // argIndex is the Sig param's position in sdkArgs (= the args array)
      const sigEntries: string[] = [];
      for (const sp of sigParams) {
        const idx = sdkArgs.findIndex((p) => p.name === sp.name);
        sigEntries.push(`${idx}: ${sp.name}`);
      }
      emit(`    return this.inner.finalizeCall(prepared, { ${sigEntries.join(', ')} });`);
      emit('  }');
    }
  }

  emit('}');
  blank();

  return lines.join('\n');
}
