/**
 * Baby Bear field arithmetic — Plonky3-generated test vector validation on regtest.
 *
 * Loads JSON test vectors generated by tests/generate-vectors/ (using Plonky3's
 * p3-baby-bear) and validates each one on-chain via compiled Bitcoin Script.
 *
 * Vectors cover: add, sub, mul, inv with edge cases, boundary values, powers
 * of 2, generator chains, and random values (829 total vectors).
 */

import { describe, it, expect } from 'vitest';
import { compileSource } from './helpers/compile.js';
import { RunarContract } from 'runar-sdk';
import { createFundedWallet } from './helpers/wallet.js';
import { createProvider } from './helpers/node.js';
import { readFileSync } from 'fs';
import { resolve } from 'path';

interface TestVector {
  op: string;
  a: number;
  b?: number;
  expected: number;
  description: string;
}

interface VectorFile {
  field: string;
  prime: number;
  vectors: TestVector[];
}

const VECTORS_DIR = resolve(import.meta.dirname, '..', '..', 'tests', 'vectors');

function loadVectors(filename: string): VectorFile {
  const data = readFileSync(resolve(VECTORS_DIR, filename), 'utf-8');
  return JSON.parse(data);
}

// Contract sources — one per operation
const bbAddSource = `
import { SmartContract, assert, bbFieldAdd } from 'runar-lang';

class BBAddVec extends SmartContract {
  readonly expected: bigint;
  constructor(expected: bigint) { super(expected); this.expected = expected; }
  public verify(a: bigint, b: bigint) {
    assert(bbFieldAdd(a, b) === this.expected);
  }
}
`;

const bbSubSource = `
import { SmartContract, assert, bbFieldSub } from 'runar-lang';

class BBSubVec extends SmartContract {
  readonly expected: bigint;
  constructor(expected: bigint) { super(expected); this.expected = expected; }
  public verify(a: bigint, b: bigint) {
    assert(bbFieldSub(a, b) === this.expected);
  }
}
`;

const bbMulSource = `
import { SmartContract, assert, bbFieldMul } from 'runar-lang';

class BBMulVec extends SmartContract {
  readonly expected: bigint;
  constructor(expected: bigint) { super(expected); this.expected = expected; }
  public verify(a: bigint, b: bigint) {
    assert(bbFieldMul(a, b) === this.expected);
  }
}
`;

const bbInvSource = `
import { SmartContract, assert, bbFieldInv } from 'runar-lang';

class BBInvVec extends SmartContract {
  readonly expected: bigint;
  constructor(expected: bigint) { super(expected); this.expected = expected; }
  public verify(a: bigint) {
    assert(bbFieldInv(a) === this.expected);
  }
}
`;

async function runBinaryVectors(
  source: string,
  fileName: string,
  vectors: TestVector[],
) {
  const artifact = compileSource(source, fileName);

  for (const vec of vectors) {
    const contract = new RunarContract(artifact, [BigInt(vec.expected)]);
    const provider = createProvider();
    const { signer } = await createFundedWallet(provider);

    await contract.deploy(provider, signer, {});
    const { txid } = await contract.call(
      'verify',
      [BigInt(vec.a), BigInt(vec.b!)],
      provider,
      signer,
    );
    expect(txid).toBeTruthy();
    expect(txid.length).toBe(64);
  }
}

async function runUnaryVectors(
  source: string,
  fileName: string,
  vectors: TestVector[],
) {
  const artifact = compileSource(source, fileName);

  for (const vec of vectors) {
    const contract = new RunarContract(artifact, [BigInt(vec.expected)]);
    const provider = createProvider();
    const { signer } = await createFundedWallet(provider);

    await contract.deploy(provider, signer, {});
    const { txid } = await contract.call(
      'verify',
      [BigInt(vec.a)],
      provider,
      signer,
    );
    expect(txid).toBeTruthy();
    expect(txid.length).toBe(64);
  }
}

describe('Baby Bear Vectors — Addition', () => {
  const vf = loadVectors('babybear_add.json');

  it(`validates ${vf.vectors.length} addition vectors on regtest`, async () => {
    await runBinaryVectors(bbAddSource, 'BBAddVec.runar.ts', vf.vectors);
  }, 600_000);
});

describe('Baby Bear Vectors — Subtraction', () => {
  const vf = loadVectors('babybear_sub.json');

  it(`validates ${vf.vectors.length} subtraction vectors on regtest`, async () => {
    await runBinaryVectors(bbSubSource, 'BBSubVec.runar.ts', vf.vectors);
  }, 600_000);
});

describe('Baby Bear Vectors — Multiplication', () => {
  const vf = loadVectors('babybear_mul.json');

  it(`validates ${vf.vectors.length} multiplication vectors on regtest`, async () => {
    await runBinaryVectors(bbMulSource, 'BBMulVec.runar.ts', vf.vectors);
  }, 600_000);
});

describe('Baby Bear Vectors — Inverse', () => {
  const vf = loadVectors('babybear_inv.json');

  it(`validates ${vf.vectors.length} inverse vectors on regtest`, async () => {
    await runUnaryVectors(bbInvSource, 'BBInvVec.runar.ts', vf.vectors);
  }, 600_000);
});
