// Generated by: runar codegen
// Source: Stateful
// Do not edit manually.

import { RunarContract, buildP2PKHScript } from 'runar-sdk';
import type { Provider, Signer, Transaction, DeployOptions } from 'runar-sdk';
import type { RunarArtifact } from 'runar-ir-schema';

type CallResult = { txid: string; tx: Transaction };

export interface TerminalOutput {
  satoshis: number;
  /** Recipient address (converted to P2PKH script). */
  address?: string;
  /** Raw locking script hex (used if address is not provided). */
  scriptHex?: string;
}

export class StatefulContract {
  private readonly inner: RunarContract;

  constructor(
    artifact: RunarArtifact,
    args: {
      count: bigint;
      maxCount: bigint;
    },
  ) {
    this.inner = new RunarContract(artifact, [args.count, args.maxCount]);
  }

  connect(provider: Provider, signer: Signer): void {
    this.inner.connect(provider, signer);
  }

  async deploy(options?: DeployOptions): Promise<CallResult>;
  async deploy(provider: Provider, signer: Signer, options?: DeployOptions): Promise<CallResult>;
  async deploy(...args: unknown[]): Promise<CallResult> {
    return (this.inner.deploy as Function)(...args);
  }

  get contract(): RunarContract {
    return this.inner;
  }

  private static resolveOutputs(outputs: TerminalOutput[]): Array<{ scriptHex: string; satoshis: number }> {
    return outputs.map((o) => {
      const scriptHex = o.scriptHex ?? buildP2PKHScript(o.address!);
      return { scriptHex, satoshis: o.satoshis };
    });
  }

  /** Terminal method: increment */
  async increment(amount: bigint, outputs: TerminalOutput[]): Promise<CallResult> {
    return this.inner.call('increment', [amount, null], {
      terminalOutputs: StatefulContract.resolveOutputs(outputs),
    });
  }

  /** Terminal method: reset */
  async reset(outputs: TerminalOutput[]): Promise<CallResult> {
    return this.inner.call('reset', [null], {
      terminalOutputs: StatefulContract.resolveOutputs(outputs),
    });
  }
}
